// src/pages/EquipmentCatalog/data.js

export const mockEquipment = [
  {
    id: 1,
    name: "Coleman Sundome 4-Person Tent",
    brand: "Coleman",
    type: "tents",
    image: "https://images.unsplash.com/photo-1633805159007-8e198bbcc931",
    imageAlt:
      "Orange Coleman Sundome tent set up in grassy camping area with trees in background",
    images: [
      "https://images.unsplash.com/photo-1722607731856-ff7d914b1be3",
      "https://images.unsplash.com/photo-1611322470518-cce1805eb6b5",
      "https://images.unsplash.com/photo-1707462273294-cca519279b7d",
    ],
    price: 150000,
    originalPrice: 200000,
    rating: 4.8,
    reviewCount: 124,
    provider: { name: "CampGear Hanoi", rating: 4.9 },
    location: "Hanoi",
    availability: "available",
    features: ["Waterproof", "Easy setup", "4-person", "Window included"],
    discount: 25,
  },
  {
    id: 2,
    name: "The North Face Dolomite Sleeping Bag -7°C",
    brand: "The North Face",
    type: "sleeping",
    image: "https://images.unsplash.com/photo-1606339777002-71a53b059c36",
    imageAlt:
      "Blue sleeping bag laid out on wooden camping platform with forest background",
    price: 80000,
    rating: 4.6,
    reviewCount: 89,
    provider: { name: "Outdoor Vietnam", rating: 4.7 },
    location: "Ho Chi Minh City",
    availability: "available",
    features: ["Warm", "Lightweight", "Moisture resistant", "Compression sack"],
  },
  {
    id: 3,
    name: "MSR PocketRocket 2 Stove",
    brand: "MSR",
    type: "cooking",
    image: "https://images.unsplash.com/photo-1727150177117-62e9ed58154e",
    imageAlt:
      "Compact camping stove with blue flame burning under metal pot in outdoor setting",
    price: 45000,
    rating: 4.9,
    reviewCount: 156,
    provider: { name: "Adventure Store", rating: 4.8 },
    location: "Da Nang",
    availability: "limited",
    features: ["Compact", "Fuel efficient", "Fast boiling", "Durable"],
  },
  {
    id: 4,
    name: "Deuter Aircontact 65+10L Trekking Backpack",
    brand: "Deuter",
    type: "backpacks",
    image: "https://images.unsplash.com/photo-1702359061641-7c59b24d905f",
    imageAlt:
      "Large green hiking backpack with multiple compartments displayed against mountain landscape",
    price: 120000,
    rating: 4.7,
    reviewCount: 78,
    provider: { name: "Mountain Gear", rating: 4.6 },
    location: "Da Lat",
    availability: "available",
    features: [
      "75L capacity",
      "Ventilated back",
      "Water-resistant",
      "Multi-compartment",
    ],
  },
  {
    id: 5,
    name: "Petzl Actik Core 450 Lumens LED Headlamp",
    brand: "Petzl",
    type: "lighting",
    image: "https://images.pexels.com/photos/2422915/pexels-photo-2422915.jpeg",
    imageAlt:
      "Bright LED headlamp with adjustable strap illuminating dark forest path at night",
    price: 35000,
    rating: 4.5,
    reviewCount: 92,
    provider: { name: "Light & Gear", rating: 4.5 },
    location: "Ha Long",
    availability: "available",
    features: [
      "USB rechargeable",
      "Water-resistant",
      "450 lumens",
      "Lightweight",
    ],
  },
  {
    id: 6,
    name: "Jetboil Flash 1L Cooking System",
    brand: "Jetboil",
    type: "cooking",
    image: "https://images.unsplash.com/photo-1516893623281-98535aaa2205",
    imageAlt:
      "Orange camping cookware system with integrated burner and insulated cup on rocky surface",
    price: 65000,
    rating: 4.8,
    reviewCount: 67,
    provider: { name: "Cook Outdoor", rating: 4.7 },
    location: "Nha Trang",
    availability: "available",
    features: ["Fast boiling", "Fuel efficient", "1L capacity", "Insulated"],
  },
  {
    id: 7,
    name: "Helinox Chair One Folding Chair",
    brand: "Helinox",
    type: "tools",
    image: "https://images.pexels.com/photos/1687845/pexels-photo-1687845.jpeg",
    imageAlt:
      "Lightweight folding camping chair in red fabric set up beside tent with mountain view",
    price: 55000,
    rating: 4.6,
    reviewCount: 45,
    provider: { name: "Comfort Camp", rating: 4.4 },
    location: "Hanoi",
    availability: "limited",
    features: ["Ultra-light", "Compact", "Comfortable", "Durable"],
  },
  {
    id: 8,
    name: "Sea to Summit Nano Mosquito Net",
    brand: "Sea to Summit",
    type: "tools",
    image: "https://images.pexels.com/photos/2662816/pexels-photo-2662816.jpeg",
    imageAlt:
      "Fine mesh mosquito net suspended over camping area with person sleeping peacefully inside",
    price: 40000,
    rating: 4.4,
    reviewCount: 38,
    provider: { name: "Bug Free Zone", rating: 4.3 },
    location: "Ho Chi Minh City",
    availability: "available",
    features: ["Ultra-light", "Fine mesh", "Easy setup", "Compact"],
  },
  {
    id: 9,
    name: "Garmin Instinct 2 Solar Outdoor Watch",
    brand: "Garmin",
    type: "tools",
    image: "https://images.unsplash.com/photo-1612831818501-9873d532fc10",
    imageAlt:
      "Rugged GPS smartwatch with solar charging displayed on rock surface",
    price: 180000,
    rating: 4.9,
    reviewCount: 203,
    provider: { name: "TechTrail", rating: 4.8 },
    location: "Hanoi",
    availability: "available",
    features: ["GPS", "Solar charging", "Heart-rate", "Waterproof 100m"],
  },
  {
    id: 10,
    name: "Therm-a-Rest NeoAir Xlite Sleeping Pad",
    brand: "Therm-a-Rest",
    type: "sleeping",
    image: "https://images.unsplash.com/photo-1629396887840-2a6b5e18a9b1",
    imageAlt:
      "Ultralight yellow sleeping pad inflated inside tent for camping comfort",
    price: 95000,
    rating: 4.8,
    reviewCount: 150,
    provider: { name: "Comfort Camp", rating: 4.5 },
    location: "Da Nang",
    availability: "available",
    features: ["Ultralight", "Insulated", "Compact", "Durable material"],
  },
  {
    id: 11,
    name: "Black Diamond Trail Pro Trekking Poles",
    brand: "Black Diamond",
    type: "tools",
    image: "https://images.unsplash.com/photo-1525981084964-5cc6556929f7",
    imageAlt: "Pair of trekking poles lying on rocky trail with mountain view",
    price: 60000,
    rating: 4.7,
    reviewCount: 88,
    provider: { name: "Mountain Gear", rating: 4.6 },
    location: "Da Lat",
    availability: "available",
    features: [
      "Adjustable length",
      "Shock absorption",
      "Aluminum",
      "Foam grip",
    ],
  },
  {
    id: 12,
    name: "Osprey Daylite Plus 20L Backpack",
    brand: "Osprey",
    type: "backpacks",
    image: "https://images.unsplash.com/photo-1609743522659-23fd6e4a78dc",
    imageAlt:
      "Small blue hiking backpack hanging on a tree with forest background",
    price: 70000,
    rating: 4.5,
    reviewCount: 54,
    provider: { name: "Adventure Store", rating: 4.7 },
    location: "Hanoi",
    availability: "available",
    features: ["20L", "Lightweight", "Padded straps", "Front pocket"],
  },
  {
    id: 13,
    name: "YETI Rambler 1L Insulated Bottle",
    brand: "YETI",
    type: "cooking",
    image: "https://images.unsplash.com/photo-1600180758890-6a5b3f3a11f8",
    imageAlt:
      "Insulated stainless steel water bottle on wooden camping table with coffee setup",
    price: 40000,
    rating: 4.9,
    reviewCount: 172,
    provider: { name: "Cook Outdoor", rating: 4.8 },
    location: "Ho Chi Minh City",
    availability: "available",
    features: [
      "Keeps drinks cold",
      "Durable steel",
      "Leak-proof",
      "1L capacity",
    ],
  },
  {
    id: 14,
    name: "ENO DoubleNest Hammock",
    brand: "ENO",
    type: "sleeping",
    image: "https://images.unsplash.com/photo-1594221557721-8e0e1cbe2041",
    imageAlt:
      "Colorful hammock strung between two trees overlooking a lake at sunset",
    price: 50000,
    rating: 4.8,
    reviewCount: 98,
    provider: { name: "Outdoor Vietnam", rating: 4.7 },
    location: "Da Nang",
    availability: "available",
    features: ["2-person", "Lightweight", "Easy setup", "Breathable fabric"],
  },
  {
    id: 15,
    name: "BioLite CampStove 2+",
    brand: "BioLite",
    type: "cooking",
    image: "https://images.unsplash.com/photo-1629396909833-99864ef60df6",
    imageAlt:
      "Compact wood-burning camping stove charging a phone while cooking outdoors",
    price: 95000,
    rating: 4.8,
    reviewCount: 112,
    provider: { name: "EcoCamp Gear", rating: 4.8 },
    location: "Hanoi",
    availability: "available",
    features: ["Wood-burning", "USB charging", "Portable", "Eco-friendly"],
  },
  {
    id: 16,
    name: "Columbia Watertight II Rain Jacket",
    brand: "Columbia",
    type: "tools",
    image: "https://images.unsplash.com/photo-1520975910057-c7d4a28bbfe7",
    imageAlt:
      "Person wearing waterproof rain jacket hiking through misty forest",
    price: 85000,
    rating: 4.6,
    reviewCount: 75,
    provider: { name: "Outdoor Vietnam", rating: 4.7 },
    location: "Ho Chi Minh City",
    availability: "available",
    features: ["Waterproof", "Breathable", "Lightweight", "Packable"],
  },
  {
    id: 17,
    name: "Naturehike Ultralight Folding Table",
    brand: "Naturehike",
    type: "tools",
    image: "https://images.unsplash.com/photo-1629397009922-43d77cf93a25",
    imageAlt:
      "Portable aluminum camping table with tea set and lantern outdoors",
    price: 45000,
    rating: 4.5,
    reviewCount: 64,
    provider: { name: "Comfort Camp", rating: 4.4 },
    location: "Da Lat",
    availability: "available",
    features: ["Foldable", "Aluminum", "Lightweight", "Durable"],
  },
  {
    id: 18,
    name: "Platypus GravityWorks 4L Water Filter",
    brand: "Platypus",
    type: "tools",
    image: "https://images.unsplash.com/photo-1618222229958-4a8e8dcf563b",
    imageAlt:
      "Gravity water filter system hanging from tree filtering water into clean reservoir",
    price: 75000,
    rating: 4.9,
    reviewCount: 90,
    provider: { name: "CampGear Hanoi", rating: 4.8 },
    location: "Hanoi",
    availability: "available",
    features: ["4L capacity", "Fast filtration", "No pumping", "Portable"],
  },
  {
    id: 19,
    name: "GSI Outdoors Pinnacle Camper Cookset",
    brand: "GSI Outdoors",
    type: "cooking",
    image: "https://images.unsplash.com/photo-1615471341251-7118f6e7c23b",
    imageAlt:
      "Compact camping cookware set with pots, pans, and bowls neatly stacked together",
    price: 115000,
    rating: 4.7,
    reviewCount: 83,
    provider: { name: "Cook Outdoor", rating: 4.7 },
    location: "Nha Trang",
    availability: "available",
    features: ["Non-stick", "Compact", "4-person", "Durable build"],
  },
  {
    id: 20,
    name: "REI Co-op Trail 25L Daypack",
    brand: "REI Co-op",
    type: "backpacks",
    image: "https://images.unsplash.com/photo-1612474052442-cce6486e6555",
    imageAlt:
      "Person wearing 25L daypack hiking up a rocky trail with scenic mountain view",
    price: 70000,
    rating: 4.6,
    reviewCount: 59,
    provider: { name: "Adventure Store", rating: 4.6 },
    location: "Da Nang",
    availability: "available",
    features: ["25L", "Hydration-compatible", "Lightweight", "Durable fabric"],
  },
];
